# Importing and parsing data from a single file

In [1]:
pwd

'C:\\Users\\tkowalcz\\Desktop\\cms-workshop'

In [2]:
import os

In [3]:
ls data

 Volume in drive C is OS
 Volume Serial Number is 462F-9A94

 Directory of C:\Users\tkowalcz\Desktop\cms-workshop\data

08/06/2019  11:51 AM    <DIR>          .
08/06/2019  11:51 AM    <DIR>          ..
08/06/2019  11:51 AM    <DIR>          data
               0 File(s)              0 bytes
               3 Dir(s)  90,266,857,472 bytes free


In [4]:
ls data\data

 Volume in drive C is OS
 Volume Serial Number is 462F-9A94

 Directory of C:\Users\tkowalcz\Desktop\cms-workshop\data\data

08/06/2019  11:51 AM    <DIR>          .
08/06/2019  11:51 AM    <DIR>          ..
08/06/2019  11:51 AM               619 benzene.xyz
08/06/2019  11:51 AM             2,471 buckminsterfullerene.xyz
08/06/2019  11:51 AM           355,359 distance_data_headers.csv
08/06/2019  11:51 AM    <DIR>          outfiles
08/06/2019  11:51 AM            61,568 sapt.out
08/06/2019  11:51 AM               155 water.xyz
               5 File(s)        420,172 bytes
               3 Dir(s)  90,266,791,936 bytes free


In [5]:
ls data\data\outfiles

 Volume in drive C is OS
 Volume Serial Number is 462F-9A94

 Directory of C:\Users\tkowalcz\Desktop\cms-workshop\data\data\outfiles

08/06/2019  11:51 AM    <DIR>          .
08/06/2019  11:51 AM    <DIR>          ..
08/06/2019  11:51 AM            12,750 butanol.out
08/06/2019  11:51 AM            18,728 decanol.out
08/06/2019  11:51 AM            10,639 ethanol.out
08/06/2019  11:51 AM            15,770 heptanol.out
08/06/2019  11:51 AM            14,767 hexanol.out
08/06/2019  11:51 AM             9,719 methanol.out
08/06/2019  11:51 AM            17,727 nonanol.out
08/06/2019  11:51 AM            16,788 octanol.out
08/06/2019  11:51 AM            13,762 pentanol.out
08/06/2019  11:51 AM            11,710 propanol.out
              10 File(s)        142,360 bytes
               2 Dir(s)  90,266,935,296 bytes free


In [56]:
# os.path.join() assembles an OS-compatible full path from underlying folder names
ethanol_path = os.path.join('data','data','outfiles','ethanol.out')
print(ethanol_path)

data\data\outfiles\ethanol.out


In [57]:
outfile = open(ethanol_path,'r')

In [58]:
data = outfile.readlines()

In [59]:
print(data)

['\n', '    -----------------------------------------------------------------------\n', '          Psi4: An Open-Source Ab Initio Electronic Structure Package\n', '                               Psi4 1.1 release\n', '\n', '                         Git: Rev {HEAD} add49b9 \n', '\n', '\n', '    R. M. Parrish, L. A. Burns, D. G. A. Smith, A. C. Simmonett,\n', '    A. E. DePrince III, E. G. Hohenstein, U. Bozkaya, A. Yu. Sokolov,\n', '    R. Di Remigio, R. M. Richard, J. F. Gonthier, A. M. James,\n', '    H. R. McAlexander, A. Kumar, M. Saitow, X. Wang, B. P. Pritchard,\n', '    P. Verma, H. F. Schaefer III, K. Patkowski, R. A. King, E. F. Valeev,\n', '    F. A. Evangelista, J. M. Turney, T. D. Crawford, and C. D. Sherrill,\n', '    J. Chem. Theory Comput. in press (2017).\n', '    (doi: 10.1021/acs.jctc.7b00174)\n', '\n', '    -----------------------------------------------------------------------\n', '\n', '\n', '    Psi4 started on: Tuesday, 27 June 2017 12:10PM\n', '\n', '    Process I

In [60]:
outfile.close()

In [61]:
print(len(data))

270


In [62]:
for line in data:
    print(line)



    -----------------------------------------------------------------------

          Psi4: An Open-Source Ab Initio Electronic Structure Package

                               Psi4 1.1 release



                         Git: Rev {HEAD} add49b9 





    R. M. Parrish, L. A. Burns, D. G. A. Smith, A. C. Simmonett,

    A. E. DePrince III, E. G. Hohenstein, U. Bozkaya, A. Yu. Sokolov,

    R. Di Remigio, R. M. Richard, J. F. Gonthier, A. M. James,

    H. R. McAlexander, A. Kumar, M. Saitow, X. Wang, B. P. Pritchard,

    P. Verma, H. F. Schaefer III, K. Patkowski, R. A. King, E. F. Valeev,

    F. A. Evangelista, J. M. Turney, T. D. Crawford, and C. D. Sherrill,

    J. Chem. Theory Comput. in press (2017).

    (doi: 10.1021/acs.jctc.7b00174)



    -----------------------------------------------------------------------





    Psi4 started on: Tuesday, 27 June 2017 12:10PM



    Process ID:  10591

    PSIDATADIR: /Users/armcdona/psi4conda/share/psi4

    Memory:     500.0 MiB

In [63]:
for line in data:
    if "Total Energy =" in line:
        energy_line = line
        print(energy_line.split('=')[1])

                       -154.0913017657301793



In [64]:
words = energy_line.split()

In [65]:
print(words)

['Total', 'Energy', '=', '-154.0913017657301793']


In [66]:
print(words[3])

-154.0913017657301793


In [67]:
energy = float(words[3])
print(energy)

-154.09130176573018


In [68]:
energy + 50

-104.09130176573018

In [69]:
for linenumber, line in enumerate(data):
    if 'Center' in line:
        print(linenumber,': ',line)

77 :         Center              X                  Y                   Z               Mass       



In [70]:
print(enumerate(data))

In [71]:
print(data[77])

       Center              X                  Y                   Z               Mass       



In [72]:
print(data[78])

    ------------   -----------------  -----------------  -----------------  -----------------



In [73]:
print(data[79])

           H          0.278612764252     1.265047047666    -1.274211449480     1.007825032070



In [74]:
atoms = []
for i in range(79,88):
    atoms.append(data[i].split()[0])

In [75]:
print(atoms)

['H', 'C', 'H', 'H', 'C', 'H', 'H', 'O', 'H']


In [76]:
coords = []
for i in range(79,88):
    co#ords.append(data[i].split()[1:4])

In [77]:
print(coords)

[['0.278612764252', '1.265047047666', '-1.274211449480'], ['0.253854764252', '1.255132047666', '-0.179502449480'], ['1.294208764252', '1.265046047666', '0.162059550520'], ['-0.241341235748', '2.165100047666', '0.170654550520'], ['-0.462006235748', '0.021161047666', '0.326687550520'], ['-1.494385235748', '0.000696047666', '-0.035023449480'], ['-0.465109235748', '0.000696047666', '1.420594550520'], ['0.212678764252', '-1.133331952334', '-0.150386449480'], ['-0.268928235748', '-1.906387952334', '0.190160550520']]


# Handling multiple files

In [78]:
# import library_name
# output = library_name.function_name(input) # how to call a function from a library
pwd

NameError: name 'pwd' is not defined

In [79]:
ls

 Volume in drive C is OS
 Volume Serial Number is 462F-9A94

 Directory of C:\Users\tkowalcz\Desktop\cms-workshop

08/08/2019  02:18 PM    <DIR>          .
08/08/2019  02:18 PM    <DIR>          ..
08/08/2019  01:31 PM    <DIR>          .ipynb_checkpoints
08/06/2019  11:51 AM    <DIR>          data
08/06/2019  11:50 AM           191,618 data.zip
08/08/2019  01:10 PM            16,748 Draft of Lesson 4 - Tables.ipynb
08/08/2019  10:57 AM            11,939 MolSSI_TeachTheTeacher_Workshop.ipynb
08/08/2019  02:18 PM            41,221 Teach-the-Teacher Demo Sessions.ipynb
               4 File(s)        261,526 bytes
               4 Dir(s)  90,241,085,440 bytes free


In [80]:
ls data\data

 Volume in drive C is OS
 Volume Serial Number is 462F-9A94

 Directory of C:\Users\tkowalcz\Desktop\cms-workshop\data\data

08/06/2019  11:51 AM    <DIR>          .
08/06/2019  11:51 AM    <DIR>          ..
08/06/2019  11:51 AM               619 benzene.xyz
08/06/2019  11:51 AM             2,471 buckminsterfullerene.xyz
08/06/2019  11:51 AM           355,359 distance_data_headers.csv
08/06/2019  11:51 AM    <DIR>          outfiles
08/06/2019  11:51 AM            61,568 sapt.out
08/06/2019  11:51 AM               155 water.xyz
               5 File(s)        420,172 bytes
               3 Dir(s)  90,241,073,152 bytes free


In [81]:
import os

In [82]:
outfile_directory = os.path.join('data','data','outfiles')
print(outfile_directory)

data\data\outfiles


In [83]:
file_location = os.path.join(outfile_directory,"*.out")
print(file_location)

data\data\outfiles\*.out


In [85]:
from glob import glob
filenames = glob(file_location)
print(filenames)

['data\\data\\outfiles\\butanol.out', 'data\\data\\outfiles\\decanol.out', 'data\\data\\outfiles\\ethanol.out', 'data\\data\\outfiles\\heptanol.out', 'data\\data\\outfiles\\hexanol.out', 'data\\data\\outfiles\\methanol.out', 'data\\data\\outfiles\\nonanol.out', 'data\\data\\outfiles\\octanol.out', 'data\\data\\outfiles\\pentanol.out', 'data\\data\\outfiles\\propanol.out']


In [90]:
energies = []
for f in filenames:
    outfile = open(f,'r')
    data = outfile.readlines()
    outfile.close()
    for line in data:
        if "Final Energy" in line:
            energy = float(line.split()[3])
            energies.append(energy)
print(energies)

[-232.1655798347283, -466.3836241400086, -154.09130176573018, -349.27397687072676, -310.2385332251633, -115.04800861868374, -427.3465180082815, -388.3110864554743, -271.20138119895074, -193.12836249728798]


In [91]:
first_file = filenames[0]
print(first_file)

data\data\outfiles\butanol.out


In [97]:
filename = os.path.basename(first_file)
molecule_name = filename.split('.')[0]
print(molecule_name)

butanol


In [105]:
energies = []
molecules = []
for f in filenames:
    # Obtain the molecule name
    filename = os.path.basename(f)
    molecule_name = filename.split('.')[0]
    molecules.append(molecule_name)
    # Read in the molecule's output file
    outfile = open(f,'r')
    data = outfile.readlines()
    outfile.close()
    # Extract the molecule's energy
    for line in data:
        if "Final Energy" in line:
            energy = float(line.split()[3])
            energies.append(energy)
    print(f'{molecule_name}: {energy}')
print(molecules,energies)

butanol: -232.1655798347283
decanol: -466.3836241400086
ethanol: -154.09130176573018
heptanol: -349.27397687072676
hexanol: -310.2385332251633
methanol: -115.04800861868374
nonanol: -427.3465180082815
octanol: -388.3110864554743
pentanol: -271.20138119895074
propanol: -193.12836249728798
['butanol', 'decanol', 'ethanol', 'heptanol', 'hexanol', 'methanol', 'nonanol', 'octanol', 'pentanol', 'propanol'] [-232.1655798347283, -466.3836241400086, -154.09130176573018, -349.27397687072676, -310.2385332251633, -115.04800861868374, -427.3465180082815, -388.3110864554743, -271.20138119895074, -193.12836249728798]


In [108]:
datafile = open(os.path.join(outfile_directory,'energies.txt'),'w')
for f in filenames:
    # Obtain the molecule name
    filename = os.path.basename(f)
    molecule_name = filename.split('.')[0]
    molecules.append(molecule_name)
    # Read in the molecule's output file
    outfile = open(f,'r')
    data = outfile.readlines()
    outfile.close()
    # Extract the molecule's energy
    for line in data:
        if "Final Energy" in line:
            energy = float(line.split()[3])
            energies.append(energy)
    print(f'{molecule_name}: {energy}')
    datafile.write(f'{molecule_name} \t {energy}\n')
print(molecules,energies)
datafile.close()

butanol: -232.1655798347283
decanol: -466.3836241400086
ethanol: -154.09130176573018
heptanol: -349.27397687072676
hexanol: -310.2385332251633
methanol: -115.04800861868374
nonanol: -427.3465180082815
octanol: -388.3110864554743
pentanol: -271.20138119895074
propanol: -193.12836249728798
['butanol', 'decanol', 'ethanol', 'heptanol', 'hexanol', 'methanol', 'nonanol', 'octanol', 'pentanol', 'propanol', 'butanol', 'decanol', 'ethanol', 'heptanol', 'hexanol', 'methanol', 'nonanol', 'octanol', 'pentanol', 'propanol', 'butanol', 'decanol', 'ethanol', 'heptanol', 'hexanol', 'methanol', 'nonanol', 'octanol', 'pentanol', 'propanol', 'butanol', 'decanol', 'ethanol', 'heptanol', 'hexanol', 'methanol', 'nonanol', 'octanol', 'pentanol', 'propanol'] [-232.1655798347283, -466.3836241400086, -154.09130176573018, -349.27397687072676, -310.2385332251633, -115.04800861868374, -427.3465180082815, -388.3110864554743, -271.20138119895074, -193.12836249728798, -232.1655798347283, -466.3836241400086, -154.091

In [110]:
import numpy
help(numpy.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings in Python 3k.  The strings
        in a 

In [111]:
import os
distance_file = os.path.join('data\data', 'distance_data_headers.csv')
distances = numpy.genfromtxt(fname=distance_file, delimiter=',', dtype='unicode')
print(distances)

[['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']
 ['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [112]:
# Extract the headers from the distance information
headers = distances[0]
print(headers)

['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']


In [113]:
# Now we'll extract the actual data with a proper slice
data = distances[1:]

In [114]:
# Remember that we imported these as type 'unicode', so they are strings.
# We need to convert these to floats before proceeding.
data = data.astype(numpy.float)
print(data)

[[1.00000e+00 8.95420e+00 5.80240e+00 1.15478e+01 9.95570e+00]
 [2.00000e+00 8.61810e+00 6.09420e+00 1.39594e+01 1.16945e+01]
 [3.00000e+00 9.00660e+00 6.06370e+00 1.30924e+01 1.13043e+01]
 ...
 [9.99800e+03 8.66250e+00 7.73060e+00 9.54690e+00 1.03063e+01]
 [9.99900e+03 9.24560e+00 7.88860e+00 9.81510e+00 1.07564e+01]
 [1.00000e+04 8.81350e+00 7.91700e+00 9.95170e+00 1.07848e+01]]


In [115]:
# Here is a subset of the data for testing
small_data = data[0:10,0:3]
print(small_data)

[[ 1.      8.9542  5.8024]
 [ 2.      8.6181  6.0942]
 [ 3.      9.0066  6.0637]
 [ 4.      9.2002  6.0227]
 [ 5.      9.1294  5.9365]
 [ 6.      9.0462  6.2553]
 [ 7.      8.8657  5.9186]
 [ 8.      9.3256  6.2351]
 [ 9.      9.4184  6.1993]
 [10.      9.06    6.0478]]


In [116]:
# Examples of slicing the small_data set to probe how slicing works
print(small_data[5,:])
print(small_data[:,1:])

[6.     9.0462 6.2553]
[[8.9542 5.8024]
 [8.6181 6.0942]
 [9.0066 6.0637]
 [9.2002 6.0227]
 [9.1294 5.9365]
 [9.0462 6.2553]
 [8.8657 5.9186]
 [9.3256 6.2351]
 [9.4184 6.1993]
 [9.06   6.0478]]


In [117]:
# Using numpy.mean() to compute the mean distance THR4_ATP
thr4_atp = data[:,1]  # Slices just the THR4_ATP column for all rows
avg_thr4_atp = numpy.mean(thr4_atp)
print(avg_thr4_atp)

10.876950930000001


In [118]:
# Determining the number of columns in the dataset (exluding timestep label)
ndatacol = len(data[1,:])
print(ndatacol)

5


In [119]:
for i in range(1,ndatacol):
    column = data[:,i]
    avg_col = numpy.mean(column)
    print(F'{headers[i]} : {avg_col}')

THR4_ATP : 10.876950930000001
THR4_ASP : 7.342344959999999
TYR6_ATP : 11.209791329999998
TYR6_ASP : 10.9934435


In [120]:
data = data.astype(numpy.float)